import { createContext, useContext, useState, useEffect } from 'react'
import { LanguageCode, LANGUAGES } from '@/lib/constants'

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string) => string
}

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    'app.name': 'Bringora',
    'app.tagline': 'Connect with Helpers in Your Community',
    'app.subtitle': 'Request help with daily tasks or earn by helping others nearby',
    'nav.requestHelp': 'Request Help',
    'nav.offerHelp': 'Offer Help',
    'nav.signOut': 'Sign Out',
    'card.requestHelp.title': 'Request Help',
    'card.requestHelp.description': 'Request assistance from nearby helpers. Quick, reliable support when you need it most.',
    'card.requestHelp.feature1': 'Real-time tracking',
    'card.requestHelp.feature2': 'Upfront pricing',
    'card.requestHelp.feature3': 'Safe & reliable',
    'card.requestHelp.button': 'Click here →',
    'card.offerHelp.title': 'Offer Help',
    'card.offerHelp.description': 'Make a difference in your community. Help others on your schedule and earn rewards.',
    'card.offerHelp.feature1': 'Flexible hours',
    'card.offerHelp.feature2': 'Weekly payouts',
    'card.offerHelp.feature3': 'In-app support',
    'card.offerHelp.button': 'Click here →',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'myRequests.title': 'My Help Requests',
    'myRequests.noRequests': 'No Requests Yet',
    'myRequests.noRequestsDesc': "You haven't created any help requests. Start by creating your first request to get help from nearby helpers.",
    'myRequests.createRequest': 'Create Request',
    'myRequests.goHome': 'Go to Homepage',
    'browseRequests.title': 'Nearby Help Requests',
    'browseRequests.subtitle': 'These people need your help in your service area',
    'browseRequests.noRequests': 'No Requests Available',
    'browseRequests.noRequestsDesc': 'There are no help requests in your area at the moment. Check back later or create your own request to get help.',
    'browseRequests.goHome': 'Go to Homepage',
    'browseRequests.contact': 'Contact',
    'browseRequests.viewDetails': 'View Details',
    'browseRequests.kmAway': 'km away',
    'requestHelp.submitSuccess': 'Request submitted successfully!',
    'requestHelp.submitError': 'Failed to submit request',
    'requestHelp.goHome': 'Go to Homepage',
    'requestHelp.editRequest': 'Edit Request',
    'requestHelp.submitRequest': 'Submit Request',
    'requestHelp.continueSummary': 'Continue to Summary',
    'requestHelp.cancel': 'Cancel',
    'common.status.pending': 'Pending',
    'common.status.accepted': 'Accepted',
    'common.status.completed': 'Completed',
    'common.status.cancelled': 'Cancelled',
  },
  te: {
    'app.name': 'బ్రింగోరా',
    'app.tagline': 'మీ కమ్యూనిటీలో సహాయకులతో కనెక్ట్ అవండి',
    'app.subtitle': 'రోజువారీ పనులకు సహాయం అభ్యర్థించండి లేదా సమీపంలో ఇతరులకు సహాయం చేసి సంపాదించండి',
    'nav.requestHelp': 'సహాయం అభ్యర్థించండి',
    'nav.offerHelp': 'సహాయం అందించండి',
    'nav.signOut': 'సైన్ అవుట్',
    'card.requestHelp.title': 'సహాయం అభ్యర్థించండి',
    'card.requestHelp.description': 'సమీపంలోని సహాయకుల నుండి సహాయం అభ్యర్థించండి. మీకు అవసరమైనప్పుడు వేగవంతమైన, నమ్మకమైన మద్దతు.',
    'card.requestHelp.feature1': 'రియల్-టైమ్ ట్రాకింగ్',
    'card.requestHelp.feature2': 'ముందస్తు ధర',
    'card.requestHelp.feature3': 'సురక్షితమైన మరియు నమ్మకమైన',
    'card.requestHelp.button': 'ఇక్కడ క్లిక్ చేయండి →',
    'card.offerHelp.title': 'సహాయం అందించండి',
    'card.offerHelp.description': 'మీ కమ్యూనిటీలో తేడా చేయండి. మీ షెడ్యూల్ ప్రకారం ఇతరులకు సహాయం చేసి రివార్డ్‌లను సంపాదించండి.',
    'card.offerHelp.feature1': 'అనువైన గంటలు',
    'card.offerHelp.feature2': 'వారానికి చెల్లింపులు',
    'card.offerHelp.feature3': 'అప్-ఇన్ మద్దతు',
    'card.offerHelp.button': 'ఇక్కడ క్లిక్ చేయండి →',
    'myRequests.title': 'నా సహాయ అభ్యర్థనలు',
    'myRequests.noRequests': 'ఇంకా అభ్యర్థనలు లేవు',
    'myRequests.noRequestsDesc': 'మీరు ఇంకా ఏ సహాయ అభ్యర్థనలను సృష్టించలేదు. సమీపంలోని సహాయకుల నుండి సహాయం పొందడానికి మీ మొదటి అభ్యర్థనను సృష్టించండి.',
    'myRequests.createRequest': 'అభ్యర్థన సృష్టించండి',
    'myRequests.goHome': 'హోమ్ పేజీకి వెళ్ళండి',
    'browseRequests.title': 'సమీప సహాయ అభ్యర్థనలు',
    'browseRequests.subtitle': 'ఈ వ్యక్తులు మీ సేవా ప్రాంతంలో మీ సహాయం కావాలి',
    'browseRequests.noRequests': 'అభ్యర్థనలు అందుబాటులో లేవు',
    'browseRequests.noRequestsDesc': 'ప్రస్తుతం మీ ప్రాంతంలో సహాయ అభ్యర్థనలు లేవు. తర్వాత తనిఖీ చేయండి లేదా సహాయం పొందడానికి మీ స్వంత అభ్యర్థనను సృష్టించండి.',
    'browseRequests.goHome': 'హోమ్ పేజీకి వెళ్ళండి',
    'browseRequests.contact': 'సంప్రదించండి',
    'browseRequests.viewDetails': 'వివరాలను వీక్షించండి',
    'browseRequests.kmAway': 'కి.మీ దూరంలో',
    'requestHelp.submitSuccess': 'అభ్యర్థన విజయవంతంగా సమర్పించబడింది!',
    'requestHelp.submitError': 'అభ్యర్థనను సమర్పించడంలో విఫలమైంది',
    'requestHelp.goHome': 'హోమ్ పేజీకి వెళ్ళండి',
    'requestHelp.editRequest': 'అభ్యర్థనను సవరించండి',
    'requestHelp.submitRequest': 'అభ్యర్థనను సమర్పించండి',
    'requestHelp.continueSummary': 'సారాంశానికి కొనసాగండి',
    'requestHelp.cancel': 'రద్దు చేయండి',
    'common.status.pending': 'పెండింగ్',
    'common.status.accepted': 'అంగీకరించబడింది',
    'common.status.completed': 'పూర్తయింది',
    'common.status.cancelled': 'రద్దు చేయబడింది',
  },
  hi: {
    'app.name': 'ब्रिंगोरा',
    'app.tagline': 'अपने समुदाय में सहायकों से जुड़ें',
    'app.subtitle': 'दैनिक कार्यों के लिए सहायता मांगें या पास में दूसरों की मदद करके कमाएं',
    'nav.requestHelp': 'सहायता मांगें',
    'nav.offerHelp': 'सहायता प्रदान करें',
    'nav.signOut': 'साइन आउट',
    'card.requestHelp.title': 'सहायता मांगें',
    'card.requestHelp.description': 'पास के सहायकों से सहायता मांगें। जब आपको सबसे ज्यादा जरूरत हो तो त्वरित, विश्वसनीय सहायता।',
    'card.requestHelp.feature1': 'रियल-टाइम ट्रैकिंग',
    'card.requestHelp.feature2': 'अग्रिम मूल्य निर्धारण',
    'card.requestHelp.feature3': 'सुरक्षित और विश्वसनीय',
    'card.requestHelp.button': 'यहाँ क्लिक करें →',
    'card.offerHelp.title': 'सहायता प्रदान करें',
    'card.offerHelp.description': 'अपने समुदाय में बदलाव लाएं। अपने समय पर दूसरों की मदद करें और पुरस्कार अर्जित करें।',
    'card.offerHelp.feature1': 'लचीले घंटे',
    'card.offerHelp.feature2': 'साप्ताहिक भुगतान',
    'card.offerHelp.feature3': 'ऐप-इन सहायता',
    'card.offerHelp.button': 'यहाँ क्लिक करें →',
    'myRequests.title': 'मेरी सहायता अनुरोध',
    'myRequests.noRequests': 'अभी तक कोई अनुरोध नहीं',
    'myRequests.noRequestsDesc': 'आपने अभी तक कोई सहायता अनुरोध नहीं बनाया है। पास के सहायकों से सहायता प्राप्त करने के लिए अपना पहला अनुरोध बनाएं।',
    'myRequests.createRequest': 'अनुरोध बनाएं',
    'myRequests.goHome': 'होमपेज पर जाएं',
    'browseRequests.title': 'पास के सहायता अनुरोध',
    'browseRequests.subtitle': 'ये लोग आपके सेवा क्षेत्र में आपकी सहायता चाहते हैं',
    'browseRequests.noRequests': 'कोई अनुरोध उपलब्ध नहीं',
    'browseRequests.noRequestsDesc': 'इस समय आपके क्षेत्र में कोई सहायता अनुरोध नहीं हैं। बाद में जांचें या सहायता प्राप्त करने के लिए अपना अनुरोध बनाएं।',
    'browseRequests.goHome': 'होमपेज पर जाएं',
    'browseRequests.contact': 'संपर्क करें',
    'browseRequests.viewDetails': 'विवरण देखें',
    'browseRequests.kmAway': 'किमी दूर',
    'requestHelp.submitSuccess': 'अनुरोध सफलतापूर्वक सबमिट किया गया!',
    'requestHelp.submitError': 'अनुरोध सबमिट करने में विफल',
    'requestHelp.goHome': 'होमपेज पर जाएं',
    'requestHelp.editRequest': 'अनुरोध संपादित करें',
    'requestHelp.submitRequest': 'अनुरोध सबमिट करें',
    'requestHelp.continueSummary': 'सारांश पर जाएं',
    'requestHelp.cancel': 'रद्द करें',
    'common.status.pending': 'लंबित',
    'common.status.accepted': 'स्वीकृत',
    'common.status.completed': 'पूर्ण',
    'common.status.cancelled': 'रद्द',
  },
  kn: {
    'app.name': 'ಬ್ರಿಂಗೋರಾ',
    'app.tagline': 'ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ಸಹಾಯಕರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
    'app.subtitle': 'ದೈನಂದಿನ ಕಾರ್ಯಗಳಿಗೆ ಸಹಾಯವನ್ನು ವಿನಂತಿಸಿ ಅಥವಾ ಹತ್ತಿರದಲ್ಲಿ ಇತರರಿಗೆ ಸಹಾಯ ಮಾಡುವ ಮೂಲಕ ಗಳಿಸಿ',
    'nav.requestHelp': 'ಸಹಾಯ ವಿನಂತಿಸಿ',
    'nav.offerHelp': 'ಸಹಾಯ ನೀಡಿ',
    'nav.signOut': 'ಸೈನ್ ಔಟ್',
    'card.requestHelp.title': 'ಸಹಾಯ ವಿನಂತಿಸಿ',
    'card.requestHelp.description': 'ಹತ್ತಿರದ ಸಹಾಯಕರಿಂದ ಸಹಾಯವನ್ನು ವಿನಂತಿಸಿ. ನಿಮಗೆ ಅತ್ಯಂತ ಅಗತ್ಯವಿರುವಾಗ ತ್ವರಿತ, ವಿಶ್ವಾಸಾರ್ಹ ಬೆಂಬಲ.',
    'card.requestHelp.feature1': 'ರಿಯಲ್-ಟೈಮ್ ಟ್ರ್ಯಾಕಿಂಗ್',
    'card.requestHelp.feature2': 'ಮುಂಚಿತ ಬೆಲೆ',
    'card.requestHelp.feature3': 'ಸುರಕ್ಷಿತ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ',
    'card.requestHelp.button': 'ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ →',
    'card.offerHelp.title': 'ಸಹಾಯ ನೀಡಿ',
    'card.offerHelp.description': 'ನಿಮ್ಮ ಸಮುದಾಯದಲ್ಲಿ ವ್ಯತ್ಯಾಸ ಮಾಡಿ. ನಿಮ್ಮ ವೇಳಾಪಟ್ಟಿಯಲ್ಲಿ ಇತರರಿಗೆ ಸಹಾಯ ಮಾಡಿ ಮತ್ತು ಬಹುಮಾನಗಳನ್ನು ಗಳಿಸಿ.',
    'card.offerHelp.feature1': 'ನಮ್ಯ ಗಂಟೆಗಳು',
    'card.offerHelp.feature2': 'ವಾರಕ್ಕೆ ಪಾವತಿಗಳು',
    'card.offerHelp.feature3': 'ಅಪ್-ಇನ್ ಬೆಂಬಲ',
    'card.offerHelp.button': 'ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ →',
    'myRequests.title': 'ನನ್ನ ಸಹಾಯ ವಿನಂತಿಗಳು',
    'myRequests.noRequests': 'ಇನ್ನೂ ವಿನಂತಿಗಳು ಇಲ್ಲ',
    'myRequests.noRequestsDesc': 'ನೀವು ಇನ್ನೂ ಯಾವುದೇ ಸಹಾಯ ವಿನಂತಿಗಳನ್ನು ರಚಿಸಿಲ್ಲ. ಹತ್ತಿರದ ಸಹಾಯಕರಿಂದ ಸಹಾಯವನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಮೊದಲ ವಿನಂತಿಯನ್ನು ರಚಿಸಿ.',
    'myRequests.createRequest': 'ವಿನಂತಿ ರಚಿಸಿ',
    'myRequests.goHome': 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',
    'browseRequests.title': 'ಹತ್ತಿರದ ಸಹಾಯ ವಿನಂತಿಗಳು',
    'browseRequests.subtitle': 'ಈ ಜನರು ನಿಮ್ಮ ಸೇವಾ ಪ್ರದೇಶದಲ್ಲಿ ನಿಮ್ಮ ಸಹಾಯವನ್ನು ಬಯಸುತ್ತಾರೆ',
    'browseRequests.noRequests': 'ವಿನಂತಿಗಳು ಲಭ್ಯವಿಲ್ಲ',
    'browseRequests.noRequestsDesc': 'ಈ ಸಮಯದಲ್ಲಿ ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಸಹಾಯ ವಿನಂತಿಗಳು ಇಲ್ಲ. ನಂತರ ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಸಹಾಯವನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಸ್ವಂತ ವಿನಂತಿಯನ್ನು ರಚಿಸಿ.',
    'browseRequests.goHome': 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',
    'browseRequests.contact': 'ಸಂಪರ್ಕಿಸಿ',
    'browseRequests.viewDetails': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'browseRequests.kmAway': 'ಕಿ.ಮೀ ದೂರದಲ್ಲಿ',
    'requestHelp.submitSuccess': 'ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    'requestHelp.submitError': 'ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ',
    'requestHelp.goHome': 'ಮುಖಪುಟಕ್ಕೆ ಹೋಗಿ',
    'requestHelp.editRequest': 'ವಿನಂತಿಯನ್ನು ಸಂಪಾದಿಸಿ',
    'requestHelp.submitRequest': 'ವಿನಂತಿಯನ್ನು ಸಲ್ಲಿಸಿ',
    'requestHelp.continueSummary': 'ಸಾರಾಂಶಕ್ಕೆ ಮುಂದುವರಿಸಿ',
    'requestHelp.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.status.pending': 'ಬಾಕಿ',
    'common.status.accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    'common.status.completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'common.status.cancelled': 'ರದ್ದುಮಾಡಲಾಗಿದೆ',
  },
  ml: {
    'app.name': 'ബ്രിംഗോര',
    'app.tagline': 'നിങ്ങളുടെ കമ്മ്യൂണിറ്റിയിലെ സഹായകരുമായി കണക്റ്റ് ചെയ്യുക',
    'app.subtitle': 'ദൈനംദിന ജോലികൾക്ക് സഹായം അഭ്യർത്ഥിക്കുക അല്ലെങ്കിൽ സമീപത്തുള്ളവർക്ക് സഹായം നൽകി സമ്പാദിക്കുക',
    'nav.requestHelp': 'സഹായം അഭ്യർത്ഥിക്കുക',
    'nav.offerHelp': 'സഹായം നൽകുക',
    'nav.signOut': 'സൈൻ ഔട്ട്',
    'card.requestHelp.title': 'സഹായം അഭ്യർത്ഥിക്കുക',
    'card.requestHelp.description': 'സമീപത്തുള്ള സഹായകരിൽ നിന്ന് സഹായം അഭ്യർത്ഥിക്കുക. നിങ്ങൾക്ക് ഏറ്റവും ആവശ്യമുള്ളപ്പോൾ വേഗത്തിലുള്ള, വിശ്വസനീയമായ പിന്തുണ.',
    'card.requestHelp.feature1': 'റിയൽ-ടൈം ട്രാക്കിംഗ്',
    'card.requestHelp.feature2': 'മുൻകൂർ വിലനിർണയം',
    'card.requestHelp.feature3': 'സുരക്ഷിതവും വിശ്വസനീയവുമാണ്',
    'card.requestHelp.button': 'ഇവിടെ ക്ലിക്ക് ചെയ്യുക →',
    'card.offerHelp.title': 'സഹായം നൽകുക',
    'card.offerHelp.description': 'നിങ്ങളുടെ കമ്മ്യൂണിറ്റിയിൽ വ്യത്യാസം വരുത്തുക. നിങ്ങളുടെ ഷെഡ്യൂളിൽ മറ്റുള്ളവർക്ക് സഹായം നൽകി പ്രതിഫലം നേടുക.',
    'card.offerHelp.feature1': 'ഗണ്യമായ മണിക്കൂറുകൾ',
    'card.offerHelp.feature2': 'ആഴ്ചയിലെ പേയ്‌മെന്റുകൾ',
    'card.offerHelp.feature3': 'അപ്-ഇൻ പിന്തുണ',
    'card.offerHelp.button': 'ഇവിടെ ക്ലിക്ക് ചെയ്യുക →',
    'myRequests.title': 'എന്റെ സഹായ അഭ്യർത്ഥനകൾ',
    'myRequests.noRequests': 'ഇതുവരെ അഭ്യർത്ഥനകൾ ഇല്ല',
    'myRequests.noRequestsDesc': 'നിങ്ങൾ ഇതുവരെ ഒരു സഹായ അഭ്യർത്ഥനയും സൃഷ്ടിച്ചിട്ടില്ല. സമീപത്തുള്ള സഹായകരിൽ നിന്ന് സഹായം ലഭിക്കാൻ നിങ്ങളുടെ ആദ്യ അഭ്യർത്ഥന സൃഷ്ടിക്കുക.',
    'myRequests.createRequest': 'അഭ്യർത്ഥന സൃഷ്ടിക്കുക',
    'myRequests.goHome': 'ഹോം പേജിലേക്ക് പോകുക',
    'browseRequests.title': 'സമീപത്തുള്ള സഹായ അഭ്യർത്ഥനകൾ',
    'browseRequests.subtitle': 'ഈ ആളുകൾ നിങ്ങളുടെ സേവാ മേഖലയിൽ നിങ്ങളുടെ സഹായം ആവശ്യപ്പെടുന്നു',
    'browseRequests.noRequests': 'അഭ്യർത്ഥനകൾ ലഭ്യമല്ല',
    'browseRequests.noRequestsDesc': 'ഇപ്പോൾ നിങ്ങളുടെ പ്രദേശത്ത് സഹായ അഭ്യർത്ഥനകൾ ഇല്ല. പിന്നീട് പരിശോധിക്കുക അല്ലെങ്കിൽ സഹായം ലഭിക്കാൻ നിങ്ങളുടെ സ്വന്തം അഭ്യർത്ഥന സൃഷ്ടിക്കുക.',
    'browseRequests.goHome': 'ഹോം പേജിലേക്ക് പോകുക',
    'browseRequests.contact': 'ബന്ധപ്പെടുക',
    'browseRequests.viewDetails': 'വിശദാംശങ്ങൾ കാണുക',
    'browseRequests.kmAway': 'കി.മീ. അകലെ',
    'requestHelp.submitSuccess': 'അഭ്യർത്ഥന വിജയകരമായി സമർപ്പിച്ചു!',
    'requestHelp.submitError': 'അഭ്യർത്ഥന സമർപ്പിക്കുന്നതിൽ പരാജയപ്പെട്ടു',
    'requestHelp.goHome': 'ഹോം പേജിലേക്ക് പോകുക',
    'requestHelp.editRequest': 'അഭ്യർത്ഥന എഡിറ്റ് ചെയ്യുക',
    'requestHelp.submitRequest': 'അഭ്യർത്ഥന സമർപ്പിക്കുക',
    'requestHelp.continueSummary': 'സംഗ്രഹത്തിലേക്ക് തുടരുക',
    'requestHelp.cancel': 'റദ്ദാക്കുക',
    'common.status.pending': 'തീർച്ചപ്പെടുത്താത്ത',
    'common.status.accepted': 'സ്വീകരിച്ചു',
    'common.status.completed': 'പൂർത്തിയാക്കി',
    'common.status.cancelled': 'റദ്ദാക്കി',
  },
  ta: {
    'app.name': 'பிரிங்கோரா',
    'app.tagline': 'உங்கள் சமூகத்தில் உதவியாளர்களுடன் இணைக்கவும்',
    'app.subtitle': 'தினசரி பணிகளுக்கு உதவி கோரவும் அல்லது அருகிலுள்ளவர்களுக்கு உதவி செய்து சம்பாதிக்கவும்',
    'nav.requestHelp': 'உதவி கோரவும்',
    'nav.offerHelp': 'உதவி வழங்கவும்',
    'nav.signOut': 'வெளியேற',
    'card.requestHelp.title': 'உதவி கோரவும்',
    'card.requestHelp.description': 'அருகிலுள்ள உதவியாளர்களிடமிருந்து உதவி கோரவும். உங்களுக்கு மிகவும் தேவையானபோது விரைவான, நம்பகமான ஆதரவு.',
    'card.requestHelp.feature1': 'நேரடி கண்காணிப்பு',
    'card.requestHelp.feature2': 'முன்கூட்டிய விலை',
    'card.requestHelp.feature3': 'பாதுகாப்பான மற்றும் நம்பகமான',
    'card.requestHelp.button': 'இங்கே கிளிக் செய்யவும் →',
    'card.offerHelp.title': 'உதவி வழங்கவும்',
    'card.offerHelp.description': 'உங்கள் சமூகத்தில் மாற்றத்தை ஏற்படுத்துங்கள். உங்கள் அட்டவணையில் மற்றவர்களுக்கு உதவி செய்து வெகுமதிகளைப் பெறுங்கள்.',
    'card.offerHelp.feature1': 'நெகிழ்வான மணிநேரங்கள்',
    'card.offerHelp.feature2': 'வாராந்திர கொடுப்பனவுகள்',
    'card.offerHelp.feature3': 'ஆப்-இன் ஆதரவு',
    'card.offerHelp.button': 'இங்கே கிளிக் செய்யவும் →',
    'myRequests.title': 'எனது உதவி கோரிக்கைகள்',
    'myRequests.noRequests': 'இதுவரை கோரிக்கைகள் இல்லை',
    'myRequests.noRequestsDesc': 'நீங்கள் இதுவரை எந்த உதவி கோரிக்கையும் உருவாக்கவில்லை. அருகிலுள்ள உதவியாளர்களிடமிருந்து உதவி பெற உங்கள் முதல் கோரிக்கையை உருவாக்கவும்.',
    'myRequests.createRequest': 'கோரிக்கை உருவாக்கவும்',
    'myRequests.goHome': 'முகப்பு பக்கத்திற்குச் செல்லவும்',
    'browseRequests.title': 'அருகிலுள்ள உதவி கோரிக்கைகள்',
    'browseRequests.subtitle': 'இந்த மக்கள் உங்கள் சேவை பகுதியில் உங்கள் உதவியை விரும்புகிறார்கள்',
    'browseRequests.noRequests': 'கோரிக்கைகள் கிடைக்கவில்லை',
    'browseRequests.noRequestsDesc': 'இந்த நேரத்தில் உங்கள் பகுதியில் உதவி கோரிக்கைகள் இல்லை. பின்னர் சரிபார்க்கவும் அல்லது உதவி பெற உங்கள் சொந்த கோரிக்கையை உருவாக்கவும்.',
    'browseRequests.goHome': 'முகப்பு பக்கத்திற்குச் செல்லவும்',
    'browseRequests.contact': 'தொடர்பு கொள்ளவும்',
    'browseRequests.viewDetails': 'விவரங்களைப் பார்க்கவும்',
    'browseRequests.kmAway': 'கி.மீ. தொலைவில்',
    'requestHelp.submitSuccess': 'கோரிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    'requestHelp.submitError': 'கோரிக்கையை சமர்ப்பிக்க முடியவில்லை',
    'requestHelp.goHome': 'முகப்பு பக்கத்திற்குச் செல்லவும்',
    'requestHelp.editRequest': 'கோரிக்கையை திருத்தவும்',
    'requestHelp.submitRequest': 'கோரிக்கையை சமர்ப்பிக்கவும்',
    'requestHelp.continueSummary': 'சுருக்கத்திற்குச் செல்லவும்',
    'requestHelp.cancel': 'ரத்துசெய்',
    'common.status.pending': 'நிலுவையில்',
    'common.status.accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
    'common.status.completed': 'முடிக்கப்பட்டது',
    'common.status.cancelled': 'ரத்துசெய்யப்பட்டது',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem('language')
    if (stored && LANGUAGES.some((l) => l.code === stored)) {
      return stored as LanguageCode
    }
    return 'en'
  })

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)?.[key] || (translations.en as Record<string, string>)[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

